config/routes.rb
App1::Application.routes.draw do
  resources :games

  resources :users do
    collection do
      get :rank1
      get :rank2
      get :rank3
    end
  end

  root 'welcome#index'

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home_player, class_name: 'User'
  belongs_to :away_player, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :home_games, foreign_key: :home_player_id, class_name: 'Game'
  has_many :away_games, foreign_key: :away_player_id, class_name: 'Game'
  has_many :home_wins, -> { where('home_score > away_score') }, foreign_key: :home_player_id, class_name: 'Game'
  has_many :away_wins, -> { where('away_score > away_score') }, foreign_key: :away_player_id, class_name: 'Game'
  has_many :home_loses, -> { where('home_score < away_score') }, foreign_key: :home_player_id, class_name: 'Game'
  has_many :away_loses, -> { where('away_score < away_score') }, foreign_key: :away_player_id, class_name: 'Game'
  has_many :home_draws, -> { where('home_score = away_score') }, foreign_key: :home_player_id, class_name: 'Game'
  has_many :away_draws, -> { where('away_score = away_score') }, foreign_key: :away_player_id, class_name: 'Game'

  def from_usa?
    true
  end

  def games
    home_games + away_games
  end

  def wins
    home_wins + away_wins
  end

  def draws
    home_draws + away_draws
  end

  def loses
    home_loses + away_loses
  end

  def score
    wins.count * 2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.first
  end

  helper_method :current_user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:home_player_id, :away_player_id, :home_score, :away_score)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_ordered_users, only: [:rank1, :rank2, :rank3]

  def index
    @users = User.all
  end

  def rank1
  end

  def rank2
  end

  def rank3
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end

    def set_ordered_users
      @users = User.all.sort_by(&:score).reverse
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home_player %><br>
    <%= f.collection_select(:home_player_id, User.all, :id, :last_name) %>
  </div>
  <div class="field">
    <%= f.label :away_player %><br>
    <%= f.collection_select(:away_player_id, User.all, :id, :last_name) %>
  </div>
  <div class="field">
    <%= f.label :home_score %><br>
    <%= f.number_field :home_score %>
  </div>
  <div class="field">
    <%= f.label :away_score %><br>
    <%= f.number_field :away_score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Home player</th>
      <th>Away player</th>
      <th>Home score</th>
      <th>Away score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.home_player.last_name %></td>
        <td><%= game.away_player.last_name %></td>
        <td><%= game.home_score %></td>
        <td><%= game.away_score %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home player:</strong>
  <%= @game.home_player.last_name %>
</p>

<p>
  <strong>Away player:</strong>
  <%= @game.away_player.last_name %>
</p>

<p>
  <strong>Home score:</strong>
  <%= @game.home_score %>
</p>

<p>
  <strong>Away score:</strong>
  <%= @game.away_score %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%= link_to 'Users', users_path, class: 'navbar-brand' %>
<%= link_to 'Users Rank 1', rank1_users_path, class: 'navbar-brand' %>
<%= link_to 'Users Rank 2', rank2_users_path, class: 'navbar-brand' %>
<%= link_to 'Users Rank 3', rank3_users_path, class: 'navbar-brand' %>
<%= link_to 'Games', games_path, class: 'navbar-brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App1" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/rank1.html.erb
<table>
  <caption>Results</caption>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Score</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.score %></td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td>Players: <%= @users.count %></td>
    <td></td>
    <td></td>
  </tr>
  </tfoot>
</table>

app/views/users/rank2.html.erb
<table>
  <caption>Results</caption>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Score</th>
    <% if current_user.games.present? %>
        <th>Wins</th>
        <th>Draws</th>
        <th>Loses</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user, index| %>
      <tr class="<%= 'winner' if index.zero? %>">
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.score %></td>
        <% if user.games.present? %>
            <td><%= user.wins.count %></td>
            <td><%= user.draws.count %></td>
            <td><%= user.loses.count %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td>Players: <%= @users.count %></td>
    <td></td>
    <td></td>
    <% if current_user.games.present? %>
        <td></td>
        <td></td>
        <td></td>
    <% end %>
  </tr>
  </tfoot>
</table>

app/views/users/rank3.html.erb
<table>
  <caption>Results</caption>
  <thead>
  <tr>
    <% if current_user.from_usa? %>
        <th>First name</th>
        <th>Last name</th>
    <% else %>
        <th>Last name</th>
        <th>First name</th>
    <% end %>
    <th>Score</th>
    <% if current_user.games.present? %>
        <th>Wins</th>
        <th>Draws</th>
        <th>Loses</th>
        <th>% of wins</th>
        <th>% of draws</th>
        <th>% of loses</th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user, index| %>
      <% css_class = if index.zero? then 'winner' elsif index < 10 then 'top10' elsif index > @users.count - 3 then 'bottom3' else '' end %>
      <tr class="<%= css_class %>">
        <td class="<%= user == current_user ? 'border' : '' %>"><%= user.first_name %></td>
        <td class="<%= user == current_user ? 'border' : '' %>"><%= user.last_name %></td>
        <td><%= user.score %></td>
        <% if user.games.present? %>
            <td><%= user.wins.count %></td>
            <td><%= user.draws.count %></td>
            <td><%= user.loses.count %></td>
            <td><%= "#{number_to_percentage((user.wins.count / user.games.count.to_f) * 100, precision: 0)}" %></td>
            <td><%= "#{number_to_percentage((user.draws.count / user.games.count.to_f) * 100, precision: 0)}" %></td>
            <td><%= "#{number_to_percentage((user.loses.count / user.games.count.to_f) * 100, precision: 0)}" %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td>Players: <%= @users.count %></td>
    <td>Games: <%= Game.count %></td>
    <td></td>
    <% if current_user.games.present? %>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    <% end %>
  </tr>
  </tfoot>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<img src="http://www.coderslab.pl/img/logo.png">
<h3 class="text-center">Welcome!</h3>